apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
  annotations:
    nvidia.com/nouse-gputype: "NVIDIA-NVIDIA GeForce RTX 4070 SUPER,NVIDIA-NVIDIA GeForce RTX 4070 Ti" # Specify the blacklist card type for this job, use comma to seperate, will not launch job on specified card
    # In this job, we don't want our job to run on 4070 SUPER or 4070 Ti type of card.
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 2 # requesting 2 vGPUs
